railstutorial: "https://www.railstutorial.org/"
learnenough: "https://www.learnenough.com/"
railstutorialbook: "https://www.railstutorial.org/book"
screencasts: "https://screencasts.railstutorial.org/"
rubyonrails: "https://rubyonrails.org/"
railstutorialhelp: "https://www.railstutorial.org/help"
michaelhartl: "https://www.michaelhartl.com/"
newsrailstutorial: "https://news.railstutorial.org/"
railtutorialcontact: "https://www.railstutorial.org/contact"
max_name: 50
max_email: 255
min_password: 6
valid_email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
size: 80
p_: 1
gravatar_emails: "https://gravatar.com/emails"
gravatar_size: 50
p_page: 10
password_reset_expire: 2
max_content: 140
micropost_user: 50
max_user: 50
max_file_size: 5
content_type: ["image/jpeg", "image/gif", "image/png"]
limit_image: [500, 500]
