railstutorial: "https://www.railstutorial.org/"
learnenough: "https://www.learnenough.com/"
railstutorialbook: "https://www.railstutorial.org/book"
screencasts: "https://screencasts.railstutorial.org/"
rubyonrails: "https://rubyonrails.org/"
railstutorialhelp: "https://www.railstutorial.org/help"
